// Code generated by go generate; DO NOT EDIT.
package file

const contentSchema = `{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "_format_version": {
      "type": "string"
    },
    "_info": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "$ref": "#/definitions/Info"
    },
    "_workspace": {
      "type": "string"
    },
    "ca_certificates": {
      "items": {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "$ref": "#/definitions/CACertificate"
      },
      "type": "array"
    },
    "certificates": {
      "items": {
        "$ref": "#/definitions/Certificate"
      },
      "type": "array"
    },
    "consumers": {
      "items": {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "$ref": "#/definitions/Consumer2"
      },
      "type": "array"
    },
    "plugins": {
      "items": {
        "$ref": "#/definitions/Plugin"
      },
      "type": "array"
    },
    "services": {
      "items": {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "$ref": "#/definitions/Service"
      },
      "type": "array"
    },
    "upstreams": {
      "items": {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "$ref": "#/definitions/Upstream"
      },
      "type": "array"
    }
  },
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "ACLGroup": {
      "properties": {
        "consumer": {
          "$ref": "#/definitions/Consumer"
        },
        "created_at": {
          "type": "integer"
        },
        "group": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "ActiveHealthcheck": {
      "properties": {
        "concurrency": {
          "type": "integer"
        },
        "healthy": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/Healthy"
        },
        "http_path": {
          "type": "string"
        },
        "https_sni": {
          "type": "string"
        },
        "https_verify_certificate": {
          "type": "boolean"
        },
        "timeout": {
          "type": "integer"
        },
        "type": {
          "type": "string"
        },
        "unhealthy": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/Unhealthy"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "BasicAuth": {
      "properties": {
        "consumer": {
          "$ref": "#/definitions/Consumer"
        },
        "created_at": {
          "type": "integer"
        },
        "id": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "CACertificate": {
      "properties": {
        "cert": {
          "type": "string"
        },
        "created_at": {
          "type": "integer"
        },
        "id": {
          "type": "string"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "CIDRPort": {
      "properties": {
        "ip": {
          "type": "string"
        },
        "port": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Certificate": {
      "properties": {
        "cert": {
          "type": "string"
        },
        "created_at": {
          "type": "integer"
        },
        "id": {
          "type": "string"
        },
        "key": {
          "type": "string"
        },
        "snis": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Consumer": {
      "properties": {
        "created_at": {
          "type": "integer"
        },
        "custom_id": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "username": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Consumer2": {
      "properties": {
        "acls": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/ACLGroup"
          },
          "type": "array"
        },
        "basicauth_credentials": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/BasicAuth"
          },
          "type": "array"
        },
        "created_at": {
          "type": "integer"
        },
        "custom_id": {
          "type": "string"
        },
        "hmacauth_credentials": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/HMACAuth"
          },
          "type": "array"
        },
        "id": {
          "type": "string"
        },
        "jwt_secrets": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/JWTAuth"
          },
          "type": "array"
        },
        "keyauth_credentials": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/KeyAuth"
          },
          "type": "array"
        },
        "oauth2_credentials": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/Oauth2Credential"
          },
          "type": "array"
        },
        "plugins": {
          "items": {
            "$ref": "#/definitions/Plugin"
          },
          "type": "array"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "username": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "HMACAuth": {
      "properties": {
        "consumer": {
          "$ref": "#/definitions/Consumer"
        },
        "created_at": {
          "type": "integer"
        },
        "id": {
          "type": "string"
        },
        "secret": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Healthcheck": {
      "properties": {
        "active": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/ActiveHealthcheck"
        },
        "passive": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/PassiveHealthcheck"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Healthy": {
      "properties": {
        "http_statuses": {
          "items": {
            "type": "integer"
          },
          "type": "array"
        },
        "interval": {
          "type": "integer"
        },
        "successes": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Info": {
      "properties": {
        "select_tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "JWTAuth": {
      "properties": {
        "algorithm": {
          "type": "string"
        },
        "consumer": {
          "$ref": "#/definitions/Consumer"
        },
        "created_at": {
          "type": "integer"
        },
        "id": {
          "type": "string"
        },
        "key": {
          "type": "string"
        },
        "rsa_public_key": {
          "type": "string"
        },
        "secret": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "KeyAuth": {
      "properties": {
        "consumer": {
          "$ref": "#/definitions/Consumer"
        },
        "created_at": {
          "type": "integer"
        },
        "id": {
          "type": "string"
        },
        "key": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Oauth2Credential": {
      "properties": {
        "client_id": {
          "type": "string"
        },
        "client_secret": {
          "type": "string"
        },
        "consumer": {
          "$ref": "#/definitions/Consumer"
        },
        "created_at": {
          "type": "integer"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "redirect_uris": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "PassiveHealthcheck": {
      "properties": {
        "healthy": {
          "$ref": "#/definitions/Healthy"
        },
        "unhealthy": {
          "$ref": "#/definitions/Unhealthy"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Plugin": {
      "properties": {
        "config": {
          "additionalProperties": true,
          "type": "object"
        },
        "consumer": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/Consumer"
        },
        "created_at": {
          "type": "integer"
        },
        "enabled": {
          "type": "boolean"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "protocols": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "route": {
          "$ref": "#/definitions/Route"
        },
        "run_on": {
          "type": "string"
        },
        "service": {
          "$ref": "#/definitions/Service"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Route": {
      "properties": {
        "created_at": {
          "type": "integer"
        },
        "destinations": {
          "items": {
            "$ref": "#/definitions/CIDRPort"
          },
          "type": "array"
        },
        "headers": {
          "patternProperties": {
            ".*": {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        },
        "hosts": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "https_redirect_status_code": {
          "type": "integer"
        },
        "id": {
          "type": "string"
        },
        "methods": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "name": {
          "type": "string"
        },
        "paths": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "plugins": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/Plugin"
          },
          "type": "array"
        },
        "preserve_host": {
          "type": "boolean"
        },
        "protocols": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "regex_priority": {
          "type": "integer"
        },
        "service": {
          "$ref": "#/definitions/Service"
        },
        "snis": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "sources": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/CIDRPort"
          },
          "type": "array"
        },
        "strip_path": {
          "type": "boolean"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "updated_at": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "anyOf": [
        {
          "required": [
            "id"
          ]
        },
        {
          "required": [
            "name"
          ]
        }
      ]
    },
    "Service": {
      "properties": {
        "client_certificate": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/Certificate"
        },
        "connect_timeout": {
          "type": "integer"
        },
        "created_at": {
          "type": "integer"
        },
        "host": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "plugins": {
          "items": {
            "$ref": "#/definitions/Plugin"
          },
          "type": "array"
        },
        "port": {
          "type": "integer"
        },
        "protocol": {
          "type": "string"
        },
        "read_timeout": {
          "type": "integer"
        },
        "retries": {
          "type": "integer"
        },
        "routes": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/Route"
          },
          "type": "array"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "updated_at": {
          "type": "integer"
        },
        "write_timeout": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "anyOf": [
        {
          "required": [
            "id"
          ]
        },
        {
          "required": [
            "name"
          ]
        }
      ]
    },
    "Target": {
      "properties": {
        "created_at": {
          "type": "number"
        },
        "id": {
          "type": "string"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "target": {
          "type": "string"
        },
        "upstream": {
          "$ref": "#/definitions/Upstream"
        },
        "weight": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Unhealthy": {
      "properties": {
        "http_failures": {
          "type": "integer"
        },
        "http_statuses": {
          "items": {
            "type": "integer"
          },
          "type": "array"
        },
        "interval": {
          "type": "integer"
        },
        "tcp_failures": {
          "type": "integer"
        },
        "timeouts": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "Upstream": {
      "properties": {
        "algorithm": {
          "type": "string"
        },
        "created_at": {
          "type": "integer"
        },
        "hash_fallback": {
          "type": "string"
        },
        "hash_fallback_header": {
          "type": "string"
        },
        "hash_on": {
          "type": "string"
        },
        "hash_on_cookie": {
          "type": "string"
        },
        "hash_on_cookie_path": {
          "type": "string"
        },
        "hash_on_header": {
          "type": "string"
        },
        "healthchecks": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "$ref": "#/definitions/Healthcheck"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "slots": {
          "type": "integer"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "targets": {
          "items": {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "$ref": "#/definitions/Target"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}`
