package main

import (
	"encoding/json"
	"log"
	"os"
	"reflect"
	"text/template"

	"github.com/alecthomas/jsonschema"
	"github.com/hbagdi/deck/file"
	"github.com/hbagdi/go-kong/kong"
)

const templateContent = `// Code generated by go generate; DO NOT EDIT.
package file

const contentSchema = ` + "`{{.Schema}}`\n"

type templateData struct {
	Schema string
}

var anyOfNameOrID = []*jsonschema.Type{
	{
		Required: []string{"id"},
	},
	{
		Required: []string{"name"},
	},
}

func main() {
	var reflector jsonschema.Reflector
	reflector.ExpandedStruct = true
	reflector.TypeMapper = func(typ reflect.Type) *jsonschema.Type {
		if typ == reflect.TypeOf(kong.Configuration{}) {
			return &jsonschema.Type{
				Type:                 "object",
				Properties:           map[string]*jsonschema.Type{},
				AdditionalProperties: []byte("true"),
			}
		}
		return nil
	}
	schema := reflector.Reflect(file.Content{})
	schema.Definitions["Service"].AnyOf = anyOfNameOrID
	schema.Definitions["Route"].AnyOf = anyOfNameOrID
	jsonSchema, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		log.Fatalln(err)
	}
	tmpl := template.New("codegen")

	tmpl, err = tmpl.Parse(templateContent)
	if err != nil {
		log.Fatalln(err)
	}

	file, err := os.OpenFile("schema.go", os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		log.Fatalln(err)
	}
	err = tmpl.Execute(file, templateData{string(jsonSchema)})
	if err != nil {
		log.Fatalln(err)
	}
	err = file.Sync()
	if err != nil {
		log.Fatalln(err)
	}
	err = file.Close()
	if err != nil {
		log.Fatalln(err)
	}
}
